[project]
name = "mcp-youtrack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.3",
    "pyarrow>=21.0.0",
    "youtrack_lap"
]
